import { describe, expect, it } from "vitest";
import { buildSearchConsumerSmallSubsetContractV0Result, classifySearchConsumerActionFeatureCasebookV0ActionReadiness, type SearchConsumerActionFeatureDictionaryV0ActionRow, type SearchConsumerActionFeatureDictionaryV0DictionaryGroups, type SearchConsumerActionFeatureDictionaryV0RootFeatureRow } from "@/game/benchmark";
const group = (values: string[]) => ({ count: values.length, values });
const dictionaries: SearchConsumerActionFeatureDictionaryV0DictionaryGroups = { schemaVersions: group(["x"]), readinessStatuses: group(["x"]), rootRefs: group(["r1","r2"]), publicActionRefs: group(["a"]), actionKinds: group(["pass"]), sourceClasses: group(["none"]), targets: group(["none"]), strengthBuckets: group(["none"]), optionIndexLabels: group(["none"]), moveCountBuckets: group(["collision","single"]) };
const root = (rootRef: string, extra: Partial<SearchConsumerActionFeatureDictionaryV0RootFeatureRow> = {}) => ({ rootRef, cFp69PublicActionCount: 1, cFp72BranchingRiskBucket: "small", cFp73BudgetPressureLabel: "low", cFp74CapStatus: "in_cap", phase: "playing", round: 1, policyId: "legal", faction: "nr", deckPresetId: "starter", matchupId: "m", ...extra } as SearchConsumerActionFeatureDictionaryV0RootFeatureRow);
const action = (rootRefId: number, extra: Partial<SearchConsumerActionFeatureDictionaryV0ActionRow> = {}) => ({ rootRefId, publicActionRefId: 0, kindId: 0, ordinal: 0, moveCount: 1, sourceClassId: 0, targetId: 0, strengthBucketId: 0, optionIndexLabelId: 0, moveCountBucketId: 1, collisionCountWithinBucket: 0, hasCollision: false, hasTarget: false, hasStrengthBucket: false, hasOptionIndexLabel: false, ...extra });
const input = () => ({ suiteId: "benchmark-v1-starter-matrix-v1", runId: "cFp83", cfp80Summary: { consumerReadinessStatus: "dictionary_ready", sourceConsistency: { status: "ready" }, reconstructionStatus: "passed", reconstructionMismatchCount: 0, rootFeatureRowCount: 2, compactActionFeatureRowCount: 2, skippedRootRowCount: 0 }, cfp81Summary: { consumerReadinessStatus: "casebook_ready", sourceConsistency: { status: "ready" }, rootFeatureRowCount: 2, compactActionFeatureRowCount: 2, skippedRootRowCount: 0, countSummaries: { combinedReadinessCounts: { consumer_ready: 1, consumer_ready_high_collision: 1, consumer_ready_high_branching: 0, consumer_ready_over_budget_context: 0 } } }, dictionaries, roots: [root("r1"), root("r2")], actions: [action(0), action(1,{hasCollision:true})], skippedRoots: [], sourceReferenceCount: 13, emptySourceHashCount: 0, cfp81HashesMatch: true });
describe("search consumer small subset contract v0", () => {
  it("uses the shared cFp81 classifier and excludes mixed roots while retaining complete ready roots", () => { const value = input(); expect(classifySearchConsumerActionFeatureCasebookV0ActionReadiness({ action: value.actions[1], root: value.roots[1] })).toBe("consumer_ready_high_collision"); const result = buildSearchConsumerSmallSubsetContractV0Result(value); expect(result.selectedRoots.map(r=>r.rootRef)).toEqual(["r1"]); expect(result.selectedActions).toHaveLength(1); expect(result.exclusionCounts.high_collision_action).toBe(1); expect(result.status).toBe("subset_too_small"); });
});
