import { describe, expect, it } from "vitest";
import { buildSearchConsumerSmallSubsetContractV0Result, classifySearchConsumerActionFeatureCasebookV0ActionReadiness, validateSearchConsumerSmallSubsetContractV0Reconstruction, type SearchConsumerActionFeatureDictionaryV0ActionRow as Action, type SearchConsumerActionFeatureDictionaryV0DictionaryGroups as Dictionaries, type SearchConsumerActionFeatureDictionaryV0RootFeatureRow as Root } from "@/game/benchmark";
const g=(values:string[])=>({count:values.length,values});
const dictionaries=():Dictionaries=>({schemaVersions:g(["unused"]),readinessStatuses:g(["unused"]),rootRefs:g(["unused-root","r1","unused-root-2","r2"]),publicActionRefs:g(["unused","a1","unused2","a2"]),actionKinds:g(["unused","pass","unused2","play_card"]),sourceClasses:g(["unused","none","unused2","unit"]),targets:g(["unused","none","unused2","board_row"]),strengthBuckets:g(["unused","none","unused2","small"]),optionIndexLabels:g(["unused","none","unused2","index"]),moveCountBuckets:g(["collision","unused","single","unused2"])});
const root=(ref:string,extra:Partial<Root>={})=>({rootRef:ref,cFp69PublicActionCount:1,cFp72BranchingRiskBucket:"small",cFp73BudgetPressureLabel:"low",cFp74CapStatus:"in_cap",phase:"playing",round:1,policyId:"legal",faction:"nr",deckPresetId:"starter",matchupId:"m",...extra}as Root);
const action=(rootRefId:number,extra:Partial<Action>={})=>({rootRefId,publicActionRefId:1,kindId:1,ordinal:0,moveCount:1,sourceClassId:1,targetId:1,strengthBucketId:1,optionIndexLabelId:1,moveCountBucketId:2,collisionCountWithinBucket:0,hasCollision:false,hasTarget:false,hasStrengthBucket:false,hasOptionIndexLabel:false,...extra});
const input=()=>({suiteId:"benchmark-v1-starter-matrix-v1",runId:"cFp83",cfp80Summary:{consumerReadinessStatus:"dictionary_ready",sourceConsistency:{status:"ready"},reconstructionStatus:"passed",reconstructionMismatchCount:0,rootFeatureRowCount:2,compactActionFeatureRowCount:2,skippedRootRowCount:0},cfp81Summary:{consumerReadinessStatus:"casebook_ready",sourceConsistency:{status:"ready"},rootFeatureRowCount:2,compactActionFeatureRowCount:2,skippedRootRowCount:0,casebookRowCount:1,sliceSummaryRowCount:1,countSummaries:{combinedReadinessCounts:{consumer_ready:1,consumer_ready_high_collision:1,consumer_ready_high_branching:0,consumer_ready_over_budget_context:0}}},dictionaries:dictionaries(),roots:[root("r1"),root("r2")],actions:[action(1),action(3,{hasCollision:true})],skippedRoots:[],cfp81CasebookRows:[{}],cfp81SliceSummaries:[{}],cfp81SkippedRootSummary:{skippedRootRowCount:0},sourceReferenceCount:13,emptySourceHashCount:0,cfp81RecordedCfp80HashesMatch:true,cfp81RecordedCfp80TotalsMatch:true});
describe("search consumer small subset contract v0",()=>{
 it("remaps sparse source IDs and reconstructs their original dictionary values",()=>{const value=input(),result=buildSearchConsumerSmallSubsetContractV0Result(value),row=result.remappedActions[0]!;expect(result.selectedRoots.map(r=>r.rootRef)).toEqual(["r1"]);expect(row).toMatchObject({rootRefId:0,publicActionRefId:0,kindId:0,sourceClassId:0,targetId:0,strengthBucketId:0,optionIndexLabelId:0,moveCountBucketId:0});expect(result.projectedDictionaries.schemaVersions).toBeUndefined();expect(result.projectedDictionaries.readinessStatuses).toBeUndefined();expect(validateSearchConsumerSmallSubsetContractV0Reconstruction({originalActions:result.selectedActions,remappedActions:result.remappedActions,dictionaries:result.projectedDictionaries,sourceDictionaries:value.dictionaries})).toEqual({invalidIdCount:0,valueMismatchCount:0,status:"passed"});});
 it("keeps the shared classifier parity and closed-root selection",()=>{const value=input();expect(classifySearchConsumerActionFeatureCasebookV0ActionReadiness({action:value.actions[1]!,root:value.roots[1]!})).toBe("consumer_ready_high_collision");const result=buildSearchConsumerSmallSubsetContractV0Result(value);expect(result.actionLabelCounts).toEqual(value.cfp81Summary.countSummaries.combinedReadinessCounts);expect(result.closureMismatchCount).toBe(0);expect(result.exclusionCounts.high_collision_action).toBe(1);});
 it("fails source consistency on cFp81 casebook or slice count mismatch",()=>{const badCasebook=input();badCasebook.cfp81Summary.casebookRowCount=2;expect(buildSearchConsumerSmallSubsetContractV0Result(badCasebook).status).toBe("source_consistency_failed");const badSlices=input();badSlices.cfp81Summary.sliceSummaryRowCount=2;expect(buildSearchConsumerSmallSubsetContractV0Result(badSlices).status).toBe("source_consistency_failed");});
});
